project:
  type: website

website:
  title: "My cool website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MN-Sallaberry
     
format:
  html:
    theme: superhero
    css: styles.css



